### ISSUE TITLE
Problem type example could be less specific

### ISSUE THREAD

**Issue by jpraet** [belgif/openapi-problem#7]
Often, a default problem response will be added to REST API's, referencing the belgif/problem/v1/problem-v1.yaml#/components/responses/ProblemResponse type.

In the generated swagger doc this becomes:

![image](https://user-images.githubusercontent.com/2212615/210791915-fe8cb9a8-6ebc-41f4-87c4-8eac5cfad830.png)

This example feels a bit out of place, as it is a very specific type of problem.

An alternative more generally applicable example could be:

```
{
  "type": "urn:problem-type:belgif:internalServerError",
  "href": "https://www.belgif.be/specification/rest/api-guide/problems/internalServerError.html",
  "title": "Internal Server Error"
  "status": 500,
  "instance": "urn:uuid:123e4567-e89b-12d3-a456-426614174000"
}
```

**Comment by pvdbosch** [comment]
Discussed in WG: OK to change the problem example.
Similar for InputValidationProblem.

Having a response for status 500 when specifying generic Problem type for a 4xx code may be confusing as well. 

To try out if it's possible to override example per explicit response status code; and if it's manageable. If not we can fall back to a generic example problem type that's clearly not used in practice.

**Comment by pvdbosch** [comment]
We could also add a link in the OpenAPI documentation of a Problem or ProblemResponse to the standardized belgif URNs on https://www.belgif.be/specification/rest/api-guide/#standardized-problem-types .
Especially for a default ProblemResponse type, users need to be able to find the list of problem types that can be returned.

Alternatively, in OpenAPI 3, examples could be added for each of these types, but this would become more difficult to maintain.

**Comment by pvdbosch** [comment]
Example from schema can be overridden in response object:
```YAML
       "409":
         description: Conflict
         content:
           application/problem+json:
             schema:
               $ref: "./types.yaml#/components/schemas/Problem"
             example: {
               "custom": "example"
             }
```

However, it cannot be overridden when $ref-fing the response object:

```$ref: "./belgif/openapi-problem.yaml#/components/responses/ProblemResponse"```.

PR created for more generic examples:  https://github.com/belgif/openapi-problem/pull/13/files
